import { PB_API, ADMIN_PASSWORD } from '@services/api.js';
import { setAdminSessionPassword } from '@services/state.js';
import { requireAdmin } from '@services/auth.js';
import { showPrompt, showConfirm, showAlert, initTournamentSelector } from '@ui/uiComponents.js';

/**
 * Logic for the System Management page.
 * Provides tools for password resets and database maintenance.
 */
export async function initManagementPage() {
  const authNotice = document.getElementById('management-auth-notice');
  const toolsSection = document.getElementById('management-tools');
  const loginBtn = document.getElementById('admin-login-btn');
  const resetPassBtn = document.getElementById('mgmt-reset-pass-btn');
  const cleanupBtn = document.getElementById('mgmt-run-cleanup-btn');

  /**
   * Verifies admin credentials before displaying management tools.
   */
  const checkAuth = async () => {
    const verified = await requireAdmin('Enter Admin Password to access management tools:');
    if (verified) {
      revealTools();
    }
  };

  const revealTools = () => {
    authNotice.classList.add('hidden');
    toolsSection.classList.remove('hidden');
    loadLeagues();
    renderLogoutButton();
  };

  /**
   * Injects a logout button into the tools section to clear the admin session.
   */
  const renderLogoutButton = () => {
    if (document.getElementById('mgmt-logout-btn')) return;
    const logoutBtn = document.createElement('button');
    logoutBtn.id = 'mgmt-logout-btn';
    logoutBtn.textContent = 'Logout Admin Session';
    logoutBtn.className = 'btn-standard secondary no-print';
    logoutBtn.style = "margin-bottom: 2rem;";
    logoutBtn.onclick = () => {
      setAdminSessionPassword(null);
      toolsSection.classList.add('hidden');
      authNotice.classList.remove('hidden');
    };
    toolsSection.prepend(logoutBtn);
  };

  /**
   * Adds a subtle version indicator to the bottom of the management tools.
   */
  const renderVersionInfo = () => {
    if (document.getElementById('mgmt-ui-version')) return;
    if (window.PB_DEBUG_MODE) console.log('[Management] Rendering version footer. current state:', window.PB_DEBUG_MODE);

    const versionInfo = document.createElement('div');
    versionInfo.id = 'mgmt-ui-version';
    versionInfo.style = "margin-top: 3rem; padding-top: 1rem; border-top: 1px solid rgba(255,255,255,0.1); display: flex; justify-content: space-between; align-items: center; font-size: 0.8rem; opacity: 0.5;";

    // Debug Mode Toggle
    const debugLabel = document.createElement('label');
    debugLabel.style = "display: flex; align-items: center; gap: 8px; cursor: pointer; user-select: none;";
    debugLabel.innerHTML = `
      <input type="checkbox" id="mgmt-debug-toggle" style="margin:0;">
      <span>Debug Logs</span>
    `;
    
    const debugToggle = debugLabel.querySelector('input');
    if (window.PB_DEBUG_MODE) console.log('[Management] Syncing checkbox UI with window.PB_DEBUG_MODE:', window.PB_DEBUG_MODE);
    debugToggle.checked = Boolean(window.PB_DEBUG_MODE); // Explicitly sync state from global variable

    debugToggle.onchange = () => {
      const isEnabled = debugToggle.checked;
      if (window.PB_DEBUG_MODE || isEnabled) console.log('[Management] Debug toggle changed. New state:', isEnabled);
      window.PB_DEBUG_MODE = isEnabled;
      localStorage.setItem('pb_debug_enabled', isEnabled);
    };

    const versionText = document.createElement('span');
    versionText.textContent = `System UI Version: ${window.PB_UI_VERSION || '1.0.0'}`;

    versionInfo.appendChild(debugLabel);
    versionInfo.appendChild(versionText);
    (toolsSection.parentElement || document.body).appendChild(versionInfo);
  };

  if (loginBtn) {
    // Use addEventListener for better reliability and wrap the call 
    // to ensure the MouseEvent isn't passed as the prompt message.
    loginBtn.addEventListener('click', () => checkAuth());
  }

  // Perform an initial check on load. If no password is set or the user is already
  // authenticated, we reveal the tools immediately without a prompt.
  checkAuth();
  renderVersionInfo();

  /**
   * Populates the league selection dropdown.
   */
  async function loadLeagues() {
    try {
      const container = document.getElementById('mgmt-league-select')?.parentElement || toolsSection;

      // Inject the shared selector into the management tools.
      // We use typeFilter: null to show both Standard and Session leagues.
      await initTournamentSelector(container, {
        typeFilter: null,
        showEvents: false,
        onRefresh: () => { /* Logic is handled by the 'Reset' button click */ }
      });
    } catch (err) {
      console.error('Failed to initialize league selector for management:', err);
      showAlert('Failed to load leagues for management: ' + err.message, 'Fetch Error');
    }
  }

  /**
   * Resets the password for the selected league.
   */
  resetPassBtn.onclick = async () => {
    // Find the select element generated by the shared component
    const select = toolsSection.querySelector('.league-select-shared');
    const id = select ? select.value : null;
    if (!id) return showAlert('Please select a league first.', 'Selection Required');

    const newPass = await showPrompt('Enter a new league password (leave blank to clear the password entirely):', 'Reset Password', false);
    if (newPass === null) return; // User cancelled the prompt

    try {
      // We call updateLeague with the resetPassword flag which is handled by leagueService.php
      await PB_API.updateLeague(id, { resetPassword: true, password: newPass });
      showAlert('League password updated successfully.', 'Success');
    } catch (err) {
      showAlert('Failed to reset password: ' + err.message, 'Error');
    }
  };

  /**
   * Manually triggers the cleanup service to prune old session data.
   */
  cleanupBtn.onclick = async () => {
    const confirmed = await showConfirm(
      'Are you sure you want to run the database cleanup? This will permanently delete session-type leagues and their associated data based on the retention period.',
      'Confirm Cleanup'
    );
    
    if (!confirmed) return;

    const adminVerified = await requireAdmin('Enter Admin Password to perform database cleanup:');
    if (!adminVerified) return;

    const daysInput = await showPrompt('Enter retention period in days (leagues older than this will be deleted):', 'Cleanup Configuration', false);
    if (daysInput === null) return; // User cancelled the prompt
    const days = parseInt(daysInput, 10) || 30;

    try {
      cleanupBtn.disabled = true;
      cleanupBtn.textContent = 'Running Cleanup...';
      
      const result = await PB_API.runCleanup(days);
      showAlert(`Cleanup successful! Removed ${result.leagues_cleaned || 0} session leagues older than ${days} days.`, 'Success');
    } catch (err) {
      showAlert('Cleanup failed: ' + err.message, 'Error');
    } finally {
      cleanupBtn.disabled = false;
      cleanupBtn.textContent = 'Run Cleanup Script';
    }
  };
}